//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCIAL_ITEM
    {
        public decimal FINANCIAL_ITEM_ID { get; set; }
        public Nullable<decimal> PARTNER_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
    
        public virtual PARTNER PARTNER { get; set; }
    }
}
