//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTNER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTNER()
        {
            this.FINANCIAL_ITEM = new HashSet<FINANCIAL_ITEM>();
            this.PARTNER1 = new HashSet<PARTNER>();
        }
    
        public decimal PARTNER_ID { get; set; }
        public string PARTNER_NAME { get; set; }
        public Nullable<decimal> PARENT_PARTNER_ID { get; set; }
        public decimal FEE_PERCENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINANCIAL_ITEM> FINANCIAL_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTNER> PARTNER1 { get; set; }
        public virtual PARTNER PARTNER2 { get; set; }
    }
}
